### ISSUE TITLE
Kein Pferd kaufbar

### ISSUE THREAD

**Issue by sCorporation2022** [tn4799/AnimalInputExtension#10]
Hallo,

Leider ist es mir nicht möglich ein Pferd in irgend einer Weise in die Trainingsanlage zu bekommen:

![image](https://github.com/tn4799/AnimalInputExtension/assets/111971356/4be3cad9-5fa6-4e10-8d29-71cd94476b2d)

Ich weiß daher nicht, wie ich ein Pferd in die Anlage bekommen soll. Beim Kauftrigger kann ich nichts kaufen. Es geht einfach nichts :(

Bitte um dringende Hilfe.

PS.: Animal Input Mod habe ich installiert

**Comment by tn4799** [comment]
Du musst mit einem Pferdeanhänger zum Tierhändler fahren, dort die Pferde kaufen und dann an in den Tiertrigger fahren um die Pferde in die Produktion einzuladen.
