### ISSUE TITLE
Server Issue

### ISSUE THREAD

**Issue by jeffreyson13** [tn4799/AnimalInputExtension#5]
Hi,
wir haben Probleme damit, das Script auf einem Server zu benutzen.
Im Log steht: Invalid event id for FS22_AnimalInputExtension.AnimalInputEvent.

**Comment by tn4799** [comment]
Schickt bitte die ganze Log.txt

**Comment by jeffreyson13** [comment]
[message.txt](https://github.com/tn4799/AnimalInputExtension/files/10098188/message.txt)

Dieser Fehler wird angezeigt, wenn man versucht Tiere in die Produktion zu laden.
Die Tiere werden jedoch nicht in die Produktion übertragen.
![FS22 ProductionIssue](https://user-images.githubusercontent.com/119136425/204133438-c4531d20-0886-4af4-abe2-6969452f3607.PNG)

**Comment by 97Lukas90** [comment]
Moin, selber Fehler hier: 

[log.txt](https://github.com/tn4799/AnimalInputExtension/files/10198663/log.txt)
![aa20888f-e31a-4ce1-9ddc-6cae8bc0a156](https://user-images.githubusercontent.com/95321654/206810305-a8e11bcb-e143-4aa2-85d3-3f07b356ebde.jpg)

**Comment by tn4799** [comment]
Ich schau mal was das Problem ist.

**Comment by tn4799** [comment]
Hab den Fehler gefunden. Ich werd ne Version mit dem Fix releasen.
