### ISSUE TITLE
Animal Input Extension and Horse Training Facility mods

### ISSUE THREAD

**Issue by OSMLALOUI** [tn4799/AnimalInputExtension#8]
hello guys,

I need some help, please. I downloaded the two mods (Animal Input Extension and Horse Training Facility mods) and put them into Mods folder correctly but it does not show inside the game.
how can I resolve this problem, please?

thank you so much.

**Comment by tn4799** [comment]
Can you please send the log.txt file.

**Comment by OSMLALOUI** [comment]
[log.txt](https://github.com/tn4799/AnimalInputExtension/files/10419853/log.txt)

here you go.

**Comment by tn4799** [comment]
You need to update the game then you will see the mods. Along with a couple of other mods that you downloaded.
